version: "1.0"

services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3306:5432"


  # User microservice
  user:
    build: 
      context: .
      dockerfile: ./app/user/build/Dockerfile
    container_name: user-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      USER_SERVICE_PORT: 8000
      AUTH_SECRET: SUPERSECRETKODEBYJ4CEU
    depends_on:
      - postgres
    ports:
      - "8080:8000"

  # Employee microservice
  employee:
    build: 
      context: .
      dockerfile: ./app/employee/build/Dockerfile
    container_name: employee-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      EMPLOYEE_SERVICE_PORT: 8081
      AUTH_SECRET: SUPERSECRETKODEBYJ4CEU
    depends_on:
      - postgres
      - user
    ports:
      - "8081:8081"

  # Kong Gateway
  kong:
    image: kong:latest
    volumes:
      - ./app/api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
